CREATE TABLE /* Таблица, совместимая с GSQ v2. PADD F5 — Plus Admission Dx and Disposition, Full Five (Spinality Types) */ `gsq_padd_f5_dcd` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `trng` int(11) NOT NULL,
  `mrn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `upi` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `first` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `middle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sex` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `dob` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `doa` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `dod` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `dispn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_home` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_mobile` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `registration_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `home_address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `icd10_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ward_field` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_date` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_asa` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_acuteness` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_timing` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_an_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_an_start` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_an_end` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sx_postop_dx` text CHARACTER SET utf8 NOT NULL,
  `free_text_sx` text CHARACTER SET utf8 NOT NULL,
  `free_text_ct` text CHARACTER SET utf8 NOT NULL,
  `free_text_mri` text CHARACTER SET utf8 NOT NULL,
  `free_text_exam` text CHARACTER SET utf8 NOT NULL,
  `adm_dx` text CHARACTER SET utf8 NOT NULL,
  `spinality_type` text CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE /* Таблица, совместимая с GSQ PADD F5 v200317 — Plus Admission Dx and Disposition, Full Five (Spinality Types), ver. Mar 2020, 17. Эту таблицу сделал специально для того, чтобы переносить в FT голые экспорты. Все просто: экспортирую выдачу, сохраняю в CSV, загружаю в БД, и данные сразу становятся доступны в FT (только надо не забыть вовремя убрать из данных строку заголовка). */ `ft_form_12` (
  `col_1` text,
  `col_2` text,
  `col_3` text,
  `col_4` text,
  `col_5` text,
  `col_6` text,
  `col_7` text,
  `col_8` text,
  `col_9` text,
  `col_10` text,
  `col_11` text,
  `col_12` text,
  `col_13` text,
  `col_14` text,
  `col_15` text,
  `col_16` text,
  `col_17` text,
  `col_18` text,
  `col_19` text,
  `col_20` text,
  `col_21` text,
  `col_22` text,
  `col_23` text,
  `col_24` text,
  `col_25` text,
  `col_26` text,
  `col_27` text,
  `col_28` text,
  `col_29` text,
  `col_30` text,
  `col_31` text,
  `col_32` text,
  `col_33` text,
  `col_34` text,
  `submission_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `submission_date` datetime NOT NULL,
  `last_modified_date` datetime NOT NULL,
  `ip_address` varchar(15) DEFAULT NULL,
  `is_finalized` enum('yes','no') DEFAULT 'yes',
  PRIMARY KEY (`submission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
